APM changes implemented for app_start, foreground and background.
Countly/countly-sdk-cordova pull request #80
Opened 2020-12-09 15:12 UTC by ijunaid

- old iOS platform check was not working fixed.
- android plugin auto initialize implemented

2020-12-09 19:03 UTC, ArtursKadikis requested changes

2020-12-09 19:03 UTC, ArtursKadikis commented on src/android/CountlyCordova.java
> +    public void pluginInitialize() {
when is this called?

2020-12-09 19:03 UTC, ArtursKadikis commented on plugin.xml
> +        <param name="onload" value="true" />
what does this do?

2020-12-09 19:03 UTC, ArtursKadikis commented on index.html
> +                    Countly.appLoadingFinished();
why is this called here? app.init is called before the first screen is shown

2020-12-11 13:04 UTC, ArtursKadikis requested changes

2020-12-11 13:04 UTC, ArtursKadikis commented on CHANGELOG.md
> +* Please refer to this documentation for released work https://support.count.ly/hc/en*us/articles/360037813011*Cordova
First of, this url is broken. Second, it is not needed, remove this line

2020-12-11 13:04 UTC, ArtursKadikis commented on CHANGELOG.md
> +
Add the version number of the previous SDK release.

2020-12-11 13:04 UTC, ArtursKadikis commented on CHANGELOG.md
> +* !! Consent change !! To use remote config, you now need to give "remote-config" consent
I feel like there should be a lot more entries in this changelog.

2020-12-11 13:20 UTC, ijunaid commented on plugin.xml
> +        <param name="onload" value="true" />
This will auto initialize the plugin. if we will not add this line then the plugin will initialize on the first function call.

2020-12-11 13:22 UTC, ijunaid commented on src/android/CountlyCordova.java
> +    public void pluginInitialize() {
when plugin initialize then initialize(CordovaInterface cordova, CordovaWebView webView) function call and right after that pluginInitialize() will call.

2020-12-15 17:02 UTC, ArtursKadikis approved these changes

2020-12-15 17:11 UTC, ArtursKadikis approved these changes

2020-12-15 17:12 UTC, merged